name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Media
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: media.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          config_order: anilist, music
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 4
          plugin_anilist_limit_characters: 22
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_time_range: long
          plugin_music_top_type: artists

      - name: Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes

      - name: General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.TOKEN }}
          base: header, activity, repositories, metadata
          base_indepth: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, ejs
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes

      - name: Habits
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: habits.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: no
          config_timezone: Asia/Kolkata
